version: "3.8"
services:
  mongodb:
      image: 'mongo'

  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb


  #frontend:


